runtime: python27
api_version: 1
threadsafe: true

# [START HANDLERS]
handlers:
- url: /static
  static_dir: static
- url: /
  static_files: district.html
  upload: district\.html
- url: /getdata/census
  script: requests.app
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest